### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by bobort** [AliLozano/django-messages-extends#21]
ForeignKeys require an on_delete argument.  Please update to make it compatible with Django 2.0.

**Comment by AliLozano** [comment]
Pull request welcome :)

**Comment by mpasternak** [comment]
I'm upgrading my app to Django 2.0 and HOLY CRAP IT IS SO GOOD TO SEE YOU HERE @AliLozano , there's a dozen packages where maintainers just leave without any contact and after a few months of waiting I need to fork them. I'm working on it and I'll submit a PR soon. GOOD TO HAVE YOU HERE.

**Comment by mpasternak** [comment]
Done, please review.

**Comment by tsifrer** [comment]
Would it be possible to get this released on pypi please? :)

**Comment by mpasternak** [comment]
The update is actually buggy, I'm working on a fix now.

**Comment by AliLozano** [comment]
@mpasternak thanks for your commit, i've alredy upload it to PiPy.
