### ISSUE TITLE
publish new release

### ISSUE THREAD

**Issue by JanMalte** [AliLozano/django-messages-extends#34]
As  #32 is merged, would you mind to publish a new release to support django 4.0?

**Comment by mpasternak** [comment]
I think I have PyPI privileges but currently I want to get CI up and running again as per #35 . As soon as everything is green I'll try to create a new release.

**Comment by mpasternak** [comment]
Please test and let me know if anything's wrong

https://pypi.org/project/django-messages-extends/0.6.3/
